=== Pimentel-J/bsc-integration-projects/ssfm-java/exported_files/xml2xml/main_xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- XSD Geral -->
	<xs:include schemaLocation="ChaoFabricaSimpleTypes.xsd"/>

	<xs:element name="ShopFloor_Report">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Depositos" type="Tdepositos"/>
				<xs:element name="LinhasProducao" type="TlinhasProducao"/>
				<xs:element name="CategoriasMaterial" type="TcategoriasMaterial"/>
				<xs:element name="OrdensProducao" type="TordensProducao"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- DEPÓSITOS -->
	<xs:complexType name="Tdepositos">
		<xs:sequence>
			<xs:element name="deposito" type="Tdeposito" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- DEPÓSITO -->
	<xs:complexType name="Tdeposito">
		<xs:sequence>
			<xs:element name="codigo" type="CodigoAlfaCurto"/>
			<xs:element name="descricao" type="Descricao"/>
		</xs:sequence>
	</xs:complexType>
	<!-- LINHAS PRODUCAO -->
	<xs:complexType name="TlinhasProducao">
		<xs:sequence>
			<xs:element name="linhaProducao" type="TlinhaProducao" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- LINHA PRODUÇÃO -->
	<xs:complexType name="TlinhaProducao">
		<xs:sequence>
			<xs:element name="idLinhaProducao" type="CodigoAlfaCurto"/>
		</xs:sequence>
	</xs:complexType>
	<!-- CATEGS. MATERIAL -->
	<xs:complexType name="TcategoriasMaterial">
		<xs:sequence>
			<xs:element name="categoriaMaterial" type="TcategoriaMaterial" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- CATEG. MATERIAL -->
	<xs:complexType name="TcategoriaMaterial">
		<xs:sequence>
			<xs:element name="codigoCatMaterial" type="CodigoAlfaCurto"/>
			<xs:element name="descricao" type="Descricao"/>
		</xs:sequence>
	</xs:complexType>
	<!-- ORDENS PRODUÇÃO -->
	<xs:complexType name="TordensProducao">
		<xs:sequence>
			<xs:element name="ordemProducao" type="TordemProducao" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- ORDEM PRODUÇÃO -->
	<xs:complexType name="TordemProducao">
		<xs:sequence>
			<xs:element name="idOrdem" type="xs:integer"/>
			<xs:element name="dataEmissao" type="Calendar"/>
			<xs:element name="dataPrevistaExec" type="Calendar"/>
			<xs:element name="codigoFabProduto" type="CodigoAlfaCurto"/>
			<xs:element name="quantidade" type="xs:float"/>
			<xs:element name="estadoOrdem" type="EstadoOrdemProducao"/>
			<xs:element name="idLinhaProducao" type="CodigoAlfaCurto" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Pimentel-J/bsc-integration-projects/ssfm-java/exported_files/xml2xml/ShopFloor_Report_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xml2xml.xsl" ?>
<ShopFloor_Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="main_xml.xsd">
    <Depositos>
        <deposito>
            <codigo>CP001</codigo>
            <descricao>depósito de tábuas</descricao>
        </deposito>
        <deposito>
            <codigo>AP002</codigo>
            <descricao>depósito de granito</descricao>
        </deposito>
        <deposito>
            <codigo>BP003</codigo>
            <descricao>depósito de tubos</descricao>
        </deposito>
        <deposito>
            <codigo>ZB004</codigo>
            <descricao>depósito de tubos</descricao>
        </deposito>
    </Depositos>
    <LinhasProducao>
        <linhaProducao>
            <idLinhaProducao>LP1</idLinhaProducao>
        </linhaProducao>
        <linhaProducao>
            <idLinhaProducao>ZP2</idLinhaProducao>
        </linhaProducao>
        <linhaProducao>
            <idLinhaProducao>LP3</idLinhaProducao>
        </linhaProducao>
    </LinhasProducao>
    <CategoriasMaterial>
        <categoriaMaterial>
            <codigoCatMaterial>md</codigoCatMaterial>
            <descricao>madeira</descricao>
        </categoriaMaterial>
        <categoriaMaterial>
            <codigoCatMaterial>pd</codigoCatMaterial>
            <descricao>pedra</descricao>
        </categoriaMaterial>
        <categoriaMaterial>
            <codigoCatMaterial>cb</codigoCatMaterial>
            <descricao>cobre</descricao>
        </categoriaMaterial>
    </CategoriasMaterial>
    <OrdensProducao>
        <ordemProducao>
            <idOrdem>3530</idOrdem>
            <dataEmissao>29-12-2018</dataEmissao>
            <dataPrevistaExec>30-12-2018</dataPrevistaExec>
            <codigoFabProduto>50000106</codigoFabProduto>
            <quantidade>65000.0</quantidade>
            <estadoOrdem>PENDENTE</estadoOrdem>
            <idLinhaProducao>LP1</idLinhaProducao>
        </ordemProducao>
        <ordemProducao>
            <idOrdem>4320</idOrdem>
            <dataEmissao>20-02-2020</dataEmissao>
            <dataPrevistaExec>26-02-2020</dataPrevistaExec>
            <codigoFabProduto>32000150</codigoFabProduto>
            <quantidade>25000.0</quantidade>
            <estadoOrdem>CONCLUIDA</estadoOrdem>
            <idLinhaProducao>LP3</idLinhaProducao>
        </ordemProducao>
    </OrdensProducao>
</ShopFloor_Report>

=== Pimentel-J/bsc-integration-projects/ssfm-java/exported_files/xml2xml/XSL Output.xml
<?xml version="1.0" encoding="UTF-8"?>
<ShopFloor_Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="main_xml.xsd">
	<Depositos>
		<deposito>
			<codigo>AP002</codigo>
			<descricao>dep칩sito de granito</descricao>
		</deposito>
		<deposito>
			<codigo>BP003</codigo>
			<descricao>dep칩sito de tubos</descricao>
		</deposito>
		<deposito>
			<codigo>CP001</codigo>
			<descricao>dep칩sito de t치buas</descricao>
		</deposito>
	</Depositos>
	<LinhasProducao>
		<linhaProducao>
			<idLinhaProducao>LP1</idLinhaProducao>
		</linhaProducao>
		<linhaProducao>
			<idLinhaProducao>LP3</idLinhaProducao>
		</linhaProducao>
	</LinhasProducao>
	<CategoriasMaterial>
		<categoriaMaterial>
			<codigoCatMaterial>cb</codigoCatMaterial>
			<descricao>cobre</descricao>
		</categoriaMaterial>
	</CategoriasMaterial>
	<OrdensProducao>
		<ordemProducao>
			<idOrdem>3530</idOrdem>
			<dataEmissao>29-12-2018</dataEmissao>
			<dataPrevistaExec>30-12-2018</dataPrevistaExec>
			<codigoFabProduto>50000106</codigoFabProduto>
			<quantidade>65000.0</quantidade>
			<estadoOrdem>PENDENTE</estadoOrdem>
			<idLinhaProducao>LP1</idLinhaProducao>
		</ordemProducao>
		<!--Existem ordens com id superior ou igual a 4k-->
	</OrdensProducao>
</ShopFloor_Report>
